name: promec_gti
description: Sistema de Gestão de Oficina Mecânica
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  url_launcher: ^6.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  flutter:
    sdk: flutter

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  google_sign_in: ^6.2.1
  
  # UI e Design
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.2
  
  # Navegação
  go_router: ^17.2.2
  
  # Estado
  provider: ^6.1.1
  
  # Ícones
  lucide_icons_flutter: ^3.1.13
  
  # Formulários
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0
  
  # HTTP (para futuras integrações)
  http: ^1.1.0
  
  # Storage Local
  shared_preferences: ^2.2.2
  
  # Notificações
  fluttertoast: ^9.0.0

dev_dependencies:
  url_launcher: ^6.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  #geolocator: ^9.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png


