// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCisncWZ8VfGg90FjCH4q3xpzp8EgCQIzU',
    appId: '1:736259305429:web:613d9deb45152840f2175c',
    messagingSenderId: '736259305429',
    projectId: 'promec-gti',
    authDomain: 'promec-gti.firebaseapp.com',
    storageBucket: 'promec-gti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-HBzsZdx_lno0D_eWMoQU4KOe00-T2I',
    appId: '1:736259305429:android:cd41d7955d62c3ccf2175c',
    messagingSenderId: '736259305429',
    projectId: 'promec-gti',
    storageBucket: 'promec-gti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPFdB8uCfhPehxRiJaOjH43ruqkS_D6c',
    appId: '1:736259305429:ios:9f51458963538c24f2175c',
    messagingSenderId: '736259305429',
    projectId: 'promec-gti',
    storageBucket: 'promec-gti.firebasestorage.app',
    iosBundleId: 'com.example.promecGti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvPFdB8uCfhPehxRiJaOjH43ruqkS_D6c',
    appId: '1:736259305429:ios:9f51458963538c24f2175c',
    messagingSenderId: '736259305429',
    projectId: 'promec-gti',
    storageBucket: 'promec-gti.firebasestorage.app',
    iosBundleId: 'com.example.promecGti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCisncWZ8VfGg90FjCH4q3xpzp8EgCQIzU',
    appId: '1:736259305429:web:56efac0a66298305f2175c',
    messagingSenderId: '736259305429',
    projectId: 'promec-gti',
    authDomain: 'promec-gti.firebaseapp.com',
    storageBucket: 'promec-gti.firebasestorage.app',
  );
}
